### ISSUE TITLE
ſ italic doesn't follow f design

### ISSUE THREAD

**Issue by thlinard** [bBoxType/FiraSans#12]
Please add a descender to /longs in italic, like for /f and for /germandbls.

**Comment by carrois** [comment]
Already included in our sources ;-) for version 4.3. This update will be released by Septmeber or Oktober 2017. Hope for your understanding that we won't update earlier. Since Mozilla canceled any support for Fira we are more or less on our own concerning funding and maintenance.

**Comment by thlinard** [comment]
Great! Thanks for your hard work!

**Comment by carrois** [comment]
Sorry, this somehow slipped through our fingers. We’ll correct it if there’ll be a 4.301 ;-)

**Comment by thlinard** [comment]
I just installed the new version and I was going to comment! But the problem is the same for FiraGo, do you want I fill a issue?

**Comment by carrois** [comment]
Yes please, so it’s on the roadmap. Sorry again.

**Comment by carrois** [comment]
Please check out version 4.301. FiraGO will follow within the next days.

**Comment by thlinard** [comment]
Corrected in all weights. Perfect! Thank you very much!
