### ISSUE TITLE
There is extra space between phases, non-en language, mono typeface

### ISSUE THREAD

**Issue by dehghani-mehdi** [bBoxType/FiraSans#13]
Hi,

Really nice font, thank you !!

I like to use `FiraMono` as my primary font for my IDE/Editor (_I'm web developer_), but there is some issue with `Persian` lang. as you can see in screenshot, I didn't hit space yet, but there is huge extra space after first phase. any chance to get fixed version for `Persian` language (I don't know if this issue is exist in other languages)?

Also if I move my cursor between chars (_in Persian_), the word/phase got broken.

![fira](https://user-images.githubusercontent.com/9152330/28501280-f74dac36-6fed-11e7-8473-76c4aa4a220c.png)

Keep it up!

**Comment by carrois** [comment]
Hi.
There is no Arabic script support in FiraMono, yet. Not one single glyph ;-)
So this error occurred in the fallback font your system uses for Arabic I fear.

Anyway, we'll have a lock at our source and try to rebuild that issue. Keep you updated.

on the way_ ralph

**Comment by dehghani-mehdi** [comment]
@carrois  Any idea how this issue will be fixed?

**Comment by carrois** [comment]
Close this because Fira Mono does not support Arabic at all.
