### ISSUE TITLE
What about slashed zero instead of dotted zero in mono face?

### ISSUE THREAD

**Issue by soviet-man** [bBoxType/FiraSans#20]
What about slashed zero instead of dotted zero in mono face?

**Comment by carrois** [comment]
Maybe within the next Mono-version. Have to discuss that with the team first, though.

**Comment by carrois** [comment]
Actually there is a slashed zero accessible via the OT feature "zero" in both, Fira Sans and Mono. Does that help?

**Comment by soviet-man** [comment]
No. How can I enable this feature?

**Comment by carrois** [comment]
Depends on the program you’re using ;-)

**Comment by carrois** [comment]
Close this because the shape already exists.
