### ISSUE TITLE
What is wrong with digits?

### ISSUE THREAD

**Issue by soviet-man** [bBoxType/FiraSans#23]
What is wrong with digits? This is awful.

![default](https://user-images.githubusercontent.com/33825590/35765356-0c7e81f6-08d3-11e8-916e-e453a6f6eafa.png)

Zoom: 10x
![default](https://user-images.githubusercontent.com/33825590/35765360-1fc8a372-08d3-11e8-8355-688c8ca576d8.png)

Font = Fira Sans.
Size = 10

**Comment by atheistray** [comment]
I guess it's a hinting problem. Are you using otf files or ttf files? I remember ttf files render better on Windows, while otf have some uneven numbers as shown in your picture. But it was from an old version though. Not sure how the latest one render on PC.

**Comment by soviet-man** [comment]
I use **Manjaro Linux**. And I downloaded zip archive of this repo and unpacked it in my **~/.fonts** folder.

**Comment by soviet-man** [comment]
Are going to do something with "bouncing" digits?

![default](https://user-images.githubusercontent.com/33825590/36513599-81c3de40-1781-11e8-8b7a-35d603166ee6.png)

**Comment by atheistray** [comment]
Can you check whether you're using the otf files or ttf files? This repo has both of them. TTF files are under the WEB directory. If you're using the otf version, try the ttf version.

**Comment by carrois** [comment]
Soviet Man, we’re not going to change automatic TT hinting settings of Fira Sans for the final version, 4.3.
 
But Fira GO will have basic manual TT Hinting. Your issue should be solved by that.

**Comment by tonsky** [comment]
Wow! What’s Fira Go?

**Comment by carrois** [comment]
FiraGO is the new branch of Fira Sans. 
We added multiple script support (Arabic, Deva, Georgian, Hebrew, Thai) and, as said, basic manual TT Hinting. 
Further developments will be based on FiraGO source files, not Fira Sans.
Release very soon! :-)

**Comment by soviet-man** [comment]
@atheistray, yes, you were right. Using TTF version fixed the problem. But why is that? I heard OTF format is superior than TTF.

**Comment by soviet-man** [comment]
@carrois, new font? Very interesting!
1) What faces are going to implelement within new font? Sans? Serif? Mono? I hope it will consider all the disadvantages of Fira Sans family.
2) When will you release it?

**Comment by carrois** [comment]
> What faces are you going to implement within new font? Sans? Serif? Mono? I hope you will consider all the disadvantages of Fira Sans family.

Only the normal-width Sans/Italic for now. But it is definitely a goal to go for more widths, styles, language support etc. 
Funding is welcome, though ;)

> When will you release it?

Very soon. We’re currently finalizing our new company/website/shop: bboxtype.com.

**Comment by madig** [comment]
FWIW, the problems shown here are probably from FreeType's autohinter being very strict about number glyphs needing to align to the same font unit height to be properly hinted. As in, the flat tops and round tops in 0123456789 need to be on the same height each. Seems fine in Fira Go from what I can see on a quick scan.
