### ISSUE TITLE
Incorrect local encoding for uni0432.loclBGR (Bulgarian lower case *в*)

### ISSUE THREAD

**Issue by StefanPeev** [bBoxType/FiraSans#25]
As is seen on the pictures Cyrillic lower case **б** is incorrectly encoded as Bulgarian lower case **в** (uni0432.loclBGR) in Fira Sans Regular. It should be **uni0432** to **uni0432.loclBGR**. Otherwise Bulgarian text will be layout with a great mistake.

![fira_sans_regular_cyrillic_bgr](https://user-images.githubusercontent.com/12949369/37442002-bf6fab48-280c-11e8-8d20-83aa72835d18.png)
![fira_sans_regular_cyrillic_default](https://user-images.githubusercontent.com/12949369/37442004-bfb9ba4e-280c-11e8-9b1f-0b592239710d.jpg)
![fira_sans_regular_cyrillic_bulgarian](https://user-images.githubusercontent.com/12949369/37442003-bf93bd1c-280c-11e8-989f-0825cf4855d2.jpg)
![screenshot-localfonts eu-2018 03 15-04-33-08](https://user-images.githubusercontent.com/12949369/37442005-bfdd03dc-280c-11e8-956f-e81b441c2eb9.png)

**Comment by carrois** [comment]
Hi Stefan. Thanks for reporting. Yes, this is going to be changed as soon as possible!

**Comment by StefanPeev** [comment]
I find the problem in Fira Sans Regular but probably the problem is all over the font families.

**Comment by StefanPeev** [comment]
As far as I could see the problem no longer exists.
