### ISSUE TITLE
New ligatures (ff, ffi, etc) are still missing.

### ISSUE THREAD

**Issue by atheistray** [bBoxType/FiraSans#26]
I'm using the latest ttf fonts on my Android phone. I'm not sure why, but only the fi and fluid ligatures are working. Love your works.❤

**Comment by atheistray** [comment]
I checked the PDF files and found that the ff, ffi, ffl ligatures are in the unencoded glyph section. I think that's why they're not showing on my phone. Is there a reason why fi and fl ligatures are encoded in the Alphabetic Presentation Forms block but the other f ligatures are not? Just curious.
Many thanks.

**Comment by carrois** [comment]
Hi Ray. Please try 4.301. Now the standard liga feature implies ff, ffi, ffl as well.

**Comment by atheistray** [comment]
They're working now! Many thanks! Now it's going to take some time for me to get used to them. I'm so familiar with the older version that I find the new ff ligatures sort of “stand out”.
