### ISSUE TITLE
Missing glyph U+1D7B small capital I with stroke

### ISSUE THREAD

**Issue by atheistray** [bBoxType/FiraSans#6]
It's a nonstandard symbol in IPA, but it's used by Oxford English dictionary and Wiktionary for British pronunciation. Please consider adding it for more thorough support. Thanks!

https://en.m.wikipedia.org/wiki/Ɨ

**Comment by carrois** [comment]
Yes, we’ll add it with the next release. Thanks.

**Comment by carrois** [comment]
Added in 4.3 / resp. FiraGO
