### ISSUE TITLE
Font size troubles

### ISSUE THREAD

**Issue by ghost** [bBoxType/FiraSans#9]
I noticed problems with some sizes of font after updating to 4.2. 
They became higher than before.

![screenshot](https://cloud.githubusercontent.com/assets/3223491/24257623/63c048b2-0ffc-11e7-864c-e1e676ce6d2c.jpg)

![screenshot2](https://cloud.githubusercontent.com/assets/3223491/24258131/e054d8ce-0ffd-11e7-80e6-66a1e14a3965.jpg)

**Comment by carrois** [comment]
Seems to be a hinting issue. We experimented with different settings in previous versions.
But we’ll be able to provide a manually hinted large update “Fira Five” within the next months. 
As for that, we won’t go into this issue any further for now, hope for your understanding.

**Comment by otdaymobilu** [comment]
Thanks for feedback! I'm looking forward to it.

**Comment by carrois** [comment]
Please check FiraGO concerning Hinting issues.
